### ISSUE TITLE
数据集中box3d_depth_dense中的3D Cube depth是如何制作的？

### ISSUE THREAD

**Issue by XuelianZ** [Traffic-X/MonoUNI#10]
你好，我用像素取点工具取点Cube depth中每个目标的每个面的深度，发现深度值都是整数值，这样的话，cube depth 不会存在很大的误差吗？
![img_v3_02bd_62dcc0d8-4ef9-489f-8f20-dc91b7851c6g](https://github.com/Traffic-X/MonoUNI/assets/40563085/6967eb74-0841-4180-9fc3-c86281067c22)

同时注意到，该图在使用过程中有一个除以256的动作。
`
# rope3d.py第203行
vis_depth_generate_new = cv2.imread('{}/{}.png'.format(self.box3d_dense_depth_dir, index), -1) / 256.`

想请教一下Cube depth在制作过程中是根据公式（6）保存的绝对深度值吗？还是说是计算出z后，会根据公式（4）转换成了Normalized_depth，并且再乘以256形成的值？（目前想要通过自己的数据集制作出cube depth）
![1717149480704](https://github.com/Traffic-X/MonoUNI/assets/40563085/3c51dbc7-6ef4-44c0-be4f-55016c4b1158)
![1717149753172](https://github.com/Traffic-X/MonoUNI/assets/40563085/cfc3cc9d-9e28-4ba4-8320-99ad365768c1)

**Comment by jjrCN** [comment]
你好，感谢关注。Cube depth中储存的值是  **绝对深度值 * 256**，单位是m，所以误差不会很大，也不是normalized_depth。

**Comment by XuelianZ** [comment]
> 你好，感谢关注。Cube depth中储存的值是 **绝对深度值 * 256**，单位是m，所以误差不会很大，也不是normalized_depth。

如果是绝对深度值的话，那上图中鼠标所点位置的绝对深度 岂不是只有（59/256）？？，似乎有些不太对

**Comment by jjrCN** [comment]
你可以参照训练代码，直接使用cv2.imread(png_path, -1) / 256. 来输出对应位置的深度看下

**Comment by XuelianZ** [comment]
> 你可以参照训练代码，直接使用cv2.imread(png_path, -1) / 256. 来输出对应位置的深度看下

十分感谢，是我忽略了-1这个参数，目前得到了正确的结果
