### ISSUE TITLE
depth_loss 变成了负数

### ISSUE THREAD

**Issue by XuelianZ** [Traffic-X/MonoUNI#11]
你好，我训练模型过程中发现 depth_loss 逐渐变成了负数，我发现是loss函数laplacian_aleatoric_uncertainty_loss 中log_variance中出现负值导致的。而log_variance是由一个nn.Conv2d层输出，然后经过torch.logsumexp计算得到， 其中 nn.Conv2d的输出值没有做区间约束，torch.logsumexp计算后就可能存在负值。请问这里地方是否存在bug
![1717891747703](https://github.com/Traffic-X/MonoUNI/assets/40563085/44ec84c0-6e4d-4e71-96b7-257fbe312eb3)
![1717891933729](https://github.com/Traffic-X/MonoUNI/assets/40563085/89fc4066-54ae-4a42-8b09-5b558b2a9670)
![1717892010912](https://github.com/Traffic-X/MonoUNI/assets/40563085/d3be7413-fe80-4215-8d0c-d28d44ecbc53)
![1717892251282](https://github.com/Traffic-X/MonoUNI/assets/40563085/d7c49951-ddb1-4c90-a5e7-d1addfbd552e)

**Comment by XuelianZ** [comment]
不好意思，上诉描述有点不准确，应该是在使用 laplacian_aleatoric_uncertainty_loss函数时，ins_depth的标准差
经过了torch.logsumexp()函数处理，而vis_depth和att_depth的标准差是直接从网络层输出的

**Comment by jjrCN** [comment]
这部分代码是来自于GUPNet，这个问题我们当时也发现了，且在GUPNet的issue里作者有解答 
 https://github.com/SuperMHP/GUPNet/issues/16
做区间约束好像会掉点，时间久远有点记不清了，你可以再深入追踪一下。
