### ISSUE TITLE
测试时按步骤不能进行训练但能评估，请问这是什么情况

### ISSUE THREAD

**Issue by Thehent** [Traffic-X/MonoUNI#14]
您好，十分感谢您的分享，作为一个初学者，我想请问您如下情况是该如何解决：
![截图 2024-07-10 10-38-33](https://github.com/Traffic-X/MonoUNI/assets/172574395/faf3b8c7-5f2f-4366-9875-391040559048)

**Comment by jjrCN** [comment]
没遇到过这个现象，请补充更多信息

**Comment by Kilitoku** [comment]
我也出现了类似的情况，运行train.sh后无任何事发生
![image](https://github.com/user-attachments/assets/e7bc9cf3-f576-460d-bd4b-5285cc3e0b1a)
运行eval.sh后会出现如下报错
![image](https://github.com/user-attachments/assets/d4cab754-6f50-4f9c-ba4c-d6745b0c14d7)
根据报错来看应该cuda的版本问题，由于我的服务器显卡为RTX3090,使用的CUDA版本必须≥11.1，然而对应的pytorch必须≥1.70，这于作者提示安装的pytorch对应不上，希望作者能够告知测试的显卡型号及对应的cuda版本

**Comment by jjrCN** [comment]
我们用的是4卡V100，cuda10

**Comment by Kilitoku** [comment]
感谢作者的回复，我重新安装了pytorch1.8.0+cu111，之后我成功运行了eval.sh
![image](https://github.com/user-attachments/assets/4a6f438b-666d-4a35-a6d9-46609afd0045)
