### ISSUE TITLE
How to generate "box3d_depth_dense"?

### ISSUE THREAD

**Issue by blablawu** [Traffic-X/MonoUNI#16]
你好👋, 对你的方法非常感兴趣，我想将你们的方法尝试别的数据集, 请问"box3d_depth_dense"这个文件夹里面的深度图是怎么生成的？ 非常感谢

**Comment by jjrCN** [comment]
这块代码有些定制化，但整体流程和论文中是相同的，可以尝试自行生成障碍物的3D box深度

**Comment by blablawu** [comment]
谢谢你, 按照论文里的方法已经解决啦。。

**Comment by DashingPanda** [comment]
> 谢谢你, 按照论文里的方法已经解决啦。。

你好👋，请问能否共享一下你实现的生成box3d_depth_dense深度图的代码🤝
