### ISSUE TITLE
关于checkpoint是如何训练出来的 以及 paper 里面 e.g. Table4 中 Rope3D - Big Vehicle 的evaluate的结果

### ISSUE THREAD

**Issue by blablawu** [Traffic-X/MonoUNI#17]
你好👋，抱歉又来打扰你了。

1. 我想尝试复盘一下 Rope3D 的evaluation 的结果，请问您训练出来的checkpoint是不是用的4中类别('car', 'big_vehicle', 'pedestrian', 'cyclist')? 8中类别(['car','van','truck','bus','pedestrian','cyclist','motorcyclist', 'tricyclist'])?

2. 还有就是请问paper Table4 里面的AP_3D的部分的76.30是 big_vehicle在 easy, moderate, hard三个级别里面哪个的结果？然后方便告知一下这个结果用的IoU是多少？ threshold是0.2么？
我自己尝试跑了一下evaluation，得出来的结果其实还更好一点, 如下: 用的checkpoint评估的(不知带是不是哪里出了问题) 
3d@0.50 [78.61270861169878, 77.05494392219896, 76.97363895953612]
3d@0.25 [88.1853739927321, 86.67722135631003, 86.5919753336087]

3.然后就是Rope_score这个指标, 我自己找了一下，没找到可以生成这个参数的部分。请问您用的是不是Rope3D里面的那个公式？
就是 rope_score = (omega_1 * AP + omega_2 * S) / (omega_1 + omega_2)
是不是如果想要计算tabel4里面的 R_score  这个指标需要自己额外修改函数来计算？

抱歉问题有点多！希望得到您的回复！
祝您国庆快乐

**Comment by jjrCN** [comment]
1.用的4类别，将8类别合并成4类别了
2.IOU=0.5。我印象里Rope3D好像是不区分难度的，只有一个moderate级别，时间有点久了你可以再看下BEVHeight或Rope3D论文确认下。
3.是根据公式自行计算的

**Comment by blablawu** [comment]
非常感谢回答！！！

祝工作学习顺利！！
