### ISSUE TITLE
 Had some problems when training ...

### ISSUE THREAD

**Issue by deyang2000** [Traffic-X/MonoUNI#4]
I used 4 x TITAN X to reproduce your project.
When I try evaluation, everything goes fine. I got a result like:
![05bae153cd0a4b8d8701b4d2f7b7304](https://github.com/Traffic-X/MonoUNI/assets/129513825/b79dafd6-28e3-4659-90ca-79a09ff308db)

However, I tried to train the project several times, and encountered problems differently:

When I use 4 GPU to train the project, the training process stopped with no reason and no error report, it just like:
![image](https://github.com/Traffic-X/MonoUNI/assets/129513825/b7dd08d5-6b9d-49d1-83ff-ec354bda2f7b)

As you can see, the training ended at 2024-03-29 14:09:12,352 at the fourth epoch, with no feedback on any problems.
The later command to clean the memory with kill -9 was executed by me alone about thirty minutes later, hence this display.
I tried it a few times, and the training always stopped at the first few epochs, taking up GPU memory and only cleaning it up separately.
Before training, I reduced the batch_size to 6. By watching nvidia-smi, I was sure that it was not due to insufficient GPU memory or GPU offline problems.

When I use 2 GPU to train the project, other problems arise, such as:
![f53b4183eb1137dea032be8dcb963b7](https://github.com/Traffic-X/MonoUNI/assets/129513825/d496e82c-069f-4385-8ab4-31fc9597607a)

How to solve these problems, thank you for your advice.

**Comment by deyang2000** [comment]
Let me try to make the batch_size smaller.

**Comment by deyang2000** [comment]
![image](https://github.com/Traffic-X/MonoUNI/assets/129513825/2773defb-1107-485a-845f-e1870c42e58e)
Now I've changed batch_size to 4, but I still have a similar problem: no errors reported, but the training has stopped. At the same time, the GPU 2 is different from the other three. (I trained with four cards together)
![image](https://github.com/Traffic-X/MonoUNI/assets/129513825/76087cc9-a2d7-4521-89bd-cb1e233dd68f)
Does anyone have a similar problem? Do you have any suggestions?

**Comment by deyang2000** [comment]
I think I found the problem: during the training process, the data in the RAM will continue to increase, and each epoch will increase by nearly 20G, which makes my 64G RAM will be full at 3 epochs, resulting in the end of the training.

So far I have modified the dataloader as follows:
![image](https://github.com/Traffic-X/MonoUNI/assets/129513825/5495cfb7-634d-4ebd-a4db-55c51c65a77c)
![cd516c162a0a4bade0535f8a95e76ee](https://github.com/Traffic-X/MonoUNI/assets/129513825/f14df844-8408-4b2a-82c1-d8421dac37e9)
![695b2e6455ee8fed27d9b966906df12](https://github.com/Traffic-X/MonoUNI/assets/129513825/c59c1b9a-545e-4f30-b5c4-b189eab6889c)

![e6560c8b4297e09fb0f1df6f5ae331e](https://github.com/Traffic-X/MonoUNI/assets/129513825/610b72da-6110-4d03-9410-8eb7b67822c9)

This alleviates the problem, but it doesn't solve the problem.
Is there anyone who can help, like how you solve this problem in training?

**Comment by jjrCN** [comment]
<img width="1117" alt="截屏2024-05-14 下午1 29 27" src="https://github.com/Traffic-X/MonoUNI/assets/37108754/6e38320d-64bf-4243-a20a-0fa00ef96e7f">
Hello, the resource usage during our training is shown in the figure above for reference. batchsize=8, 4 cards for training. Hope it will help you.

**Comment by deyang2000** [comment]
Thanks for your reply. My memory seems too small, so I will try to reduce the batch size further first. If it fails, I will consider expanding the server's memory.

**Comment by NoctisJOJO** [comment]
我也是同样的问题，我在训练到第三个epoch时，就由于内存不足而停止了
![image](https://github.com/user-attachments/assets/a3a36738-434c-43eb-a657-457569f1b262)
解决办法只能是加大内存吗？

**Comment by deyang2000** [comment]
> 我也是同样的问题，我在训练到第三个epoch时，就由于内存不足而停止了 ![image](https://private-user-images.githubusercontent.com/163861739/398888905-a3a36738-434c-43eb-a657-457569f1b262.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyODg1OTAsIm5iZiI6MTczNTI4ODI5MCwicGF0aCI6Ii8xNjM4NjE3MzkvMzk4ODg4OTA1LWEzYTM2NzM4LTQzNGMtNDNlYi1hNjU3LTQ1NzU2OWYxYjI2Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyN1QwODMxMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xOTgxNzYxNzNlNTc3MDM3ODRmYzc1YjM4ZGEyY2JhZDhhZDBkOTA4YWM3ODg0MDkxMGNjMjY5YTZjY2MxMGJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.lsd-qzhdWZG9hkTv4adO9O9BywQSYLmvA3NFtbtvV8o) 解决办法只能是加大内存吗？

最简单的办法是多加几根内存条(估计要512G),或者使用部分数据集(我就是这样做的).

**Comment by NoctisJOJO** [comment]
> > 我也是同样的问题，我在训练到第三个epoch时，就由于内存不足而停止了 ![image](https://private-user-images.githubusercontent.com/163861739/398888905-a3a36738-434c-43eb-a657-457569f1b262.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyODg1OTAsIm5iZiI6MTczNTI4ODI5MCwicGF0aCI6Ii8xNjM4NjE3MzkvMzk4ODg4OTA1LWEzYTM2NzM4LTQzNGMtNDNlYi1hNjU3LTQ1NzU2OWYxYjI2Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyN1QwODMxMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xOTgxNzYxNzNlNTc3MDM3ODRmYzc1YjM4ZGEyY2JhZDhhZDBkOTA4YWM3ODg0MDkxMGNjMjY5YTZjY2MxMGJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.lsd-qzhdWZG9hkTv4adO9O9BywQSYLmvA3NFtbtvV8o) 解决办法只能是加大内存吗？
> 
> 最简单的办法是多加几根内存条(估计要512G),或者使用部分数据集(我就是这样做的).

512G也太大了。。。我是租的服务器，租一张卡给40G内存，最多租8张，这怎么也不够啊。使用部分数据集，那还能达到训练效果吗

**Comment by deyang2000** [comment]
> > > 我也是同样的问题，我在训练到第三个epoch时，就由于内存不足而停止了 ![image](https://private-user-images.githubusercontent.com/163861739/398888905-a3a36738-434c-43eb-a657-457569f1b262.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyODg1OTAsIm5iZiI6MTczNTI4ODI5MCwicGF0aCI6Ii8xNjM4NjE3MzkvMzk4ODg4OTA1LWEzYTM2NzM4LTQzNGMtNDNlYi1hNjU3LTQ1NzU2OWYxYjI2Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyN1QwODMxMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xOTgxNzYxNzNlNTc3MDM3ODRmYzc1YjM4ZGEyY2JhZDhhZDBkOTA4YWM3ODg0MDkxMGNjMjY5YTZjY2MxMGJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.lsd-qzhdWZG9hkTv4adO9O9BywQSYLmvA3NFtbtvV8o) 解决办法只能是加大内存吗？
> > 
> > 
> > 最简单的办法是多加几根内存条(估计要512G),或者使用部分数据集(我就是这样做的).
> 
> 512G也太大了。。。我是租的服务器，租一张卡给40G内存，最多租8张，这怎么也不够啊。使用部分数据集，那还能达到训练效果吗

使用部分数据集肯定没有整个数据集有说服力。可以考虑每个epoch结束对CPU内存进行合理的清理，把部分数据搬运到硬盘空间里。

**Comment by NoctisJOJO** [comment]
> > > > 我也是同样的问题，我在训练到第三个epoch时，就由于内存不足而停止了 ![image](https://private-user-images.githubusercontent.com/163861739/398888905-a3a36738-434c-43eb-a657-457569f1b262.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyODg1OTAsIm5iZiI6MTczNTI4ODI5MCwicGF0aCI6Ii8xNjM4NjE3MzkvMzk4ODg4OTA1LWEzYTM2NzM4LTQzNGMtNDNlYi1hNjU3LTQ1NzU2OWYxYjI2Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyN1QwODMxMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xOTgxNzYxNzNlNTc3MDM3ODRmYzc1YjM4ZGEyY2JhZDhhZDBkOTA4YWM3ODg0MDkxMGNjMjY5YTZjY2MxMGJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.lsd-qzhdWZG9hkTv4adO9O9BywQSYLmvA3NFtbtvV8o) 解决办法只能是加大内存吗？
> > > 
> > > 
> > > 最简单的办法是多加几根内存条(估计要512G),或者使用部分数据集(我就是这样做的).
> > 
> > 
> > 512G也太大了。。。我是租的服务器，租一张卡给40G内存，最多租8张，这怎么也不够啊。使用部分数据集，那还能达到训练效果吗
> 
> 使用部分数据集肯定没有整个数据集有说服力。可以考虑每个epoch结束对CPU内存进行合理的清理，把部分数据搬运到硬盘空间里。

我也是这么想，每个epoch后清理一下缓存。我试了加个 torch.cuda.empty_cache()，但是没变化。其他的就不会改了，代码能力太差了。

**Comment by deyang2000** [comment]
> > > > > 我也是同样的问题，我在训练到第三个epoch时，就由于内存不足而停止了 ![image](https://private-user-images.githubusercontent.com/163861739/398888905-a3a36738-434c-43eb-a657-457569f1b262.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyODg1OTAsIm5iZiI6MTczNTI4ODI5MCwicGF0aCI6Ii8xNjM4NjE3MzkvMzk4ODg4OTA1LWEzYTM2NzM4LTQzNGMtNDNlYi1hNjU3LTQ1NzU2OWYxYjI2Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyN1QwODMxMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xOTgxNzYxNzNlNTc3MDM3ODRmYzc1YjM4ZGEyY2JhZDhhZDBkOTA4YWM3ODg0MDkxMGNjMjY5YTZjY2MxMGJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.lsd-qzhdWZG9hkTv4adO9O9BywQSYLmvA3NFtbtvV8o) 解决办法只能是加大内存吗？
> > > > 
> > > > 
> > > > 最简单的办法是多加几根内存条(估计要512G),或者使用部分数据集(我就是这样做的).
> > > 
> > > 
> > > 512G也太大了。。。我是租的服务器，租一张卡给40G内存，最多租8张，这怎么也不够啊。使用部分数据集，那还能达到训练效果吗
> > 
> > 
> > 使用部分数据集肯定没有整个数据集有说服力。可以考虑每个epoch结束对CPU内存进行合理的清理，把部分数据搬运到硬盘空间里。
> 
> 我也是这么想，每个epoch后清理一下缓存。我试了加个 torch.cuda.empty_cache()，但是没变化。其他的就不会改了，代码能力太差了。

最好还是用大内存解决，一般大学公用的八卡服务器内存都在一个T以上。

**Comment by mingjunjun** [comment]
你们有完全训练完吗？我用源代码单卡训练全部数据集，参数都没有修改，训练150轮得到的结果跟论文里差距很大，得不到它训练的checkpoints评估得到的效果
![monouni](https://github.com/user-attachments/assets/eaf4a1b5-e6d9-46c0-8c19-335f13bd0e00)

**Comment by deyang2000** [comment]
![image](https://github.com/user-attachments/assets/5dc217a3-80b0-4662-944b-49f852fc3799)
由于CPU内存不够，这是用了大概三分之一数据进行训练的结果。

> 你们有完全训练完吗？我用源代码单卡训练全部数据集，参数都没有修改，训练150轮得到的结果跟论文里差距很大，得不到它训练的checkpoints评估得到的效果 ![monouni](https://private-user-images.githubusercontent.com/152282641/400419314-eaf4a1b5-e6d9-46c0-8c19-335f13bd0e00.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYxNjYyNzMsIm5iZiI6MTczNjE2NTk3MywicGF0aCI6Ii8xNTIyODI2NDEvNDAwNDE5MzE0LWVhZjRhMWI1LWU2ZDktNDZjMC04YzE5LTMzNWYxM2JkMGUwMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwNlQxMjE5MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zM2JiMDU2ZmRlNGY5MTAwMjM0ZmJhMmJjZmY1MmQ2MTVmZjU3ZmM0OWU0MjMzYTgxOWNiNWQ4ZjljZTdiODgzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.tF_PY-2PD4iXchNrLl1J-t89Tb0B_pkcwks6ATkO_fc)

**Comment by mingjunjun** [comment]
可以分享一下你的系统设置吗？我代码能力稍微差一点希望能够相互沟通一下

**Comment by mingjunjun** [comment]
> ![image](https://private-user-images.githubusercontent.com/129513825/400421512-5dc217a3-80b0-4662-944b-49f852fc3799.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYxNjcxMzMsIm5iZiI6MTczNjE2NjgzMywicGF0aCI6Ii8xMjk1MTM4MjUvNDAwNDIxNTEyLTVkYzIxN2EzLTgwYjAtNDY2Mi05NDRiLTQ5Zjg1MmZjMzc5OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwNlQxMjMzNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NTM0NTNjYWY3MTAxMTA0ZmNhYzkyNTNmNTZhMGE1ZDI4NmY5N2EwZmJhNTMzNDg5Y2M5YWI2YTU5ZmJlMTc5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9._VBxj9ixGe20Fdm23ZejQbkfO68QX2V1195M4bdr8EQ) 由于CPU内存不够，这是用了大概三分之一数据进行训练的结果。
> 
> > 你们有完全训练完吗？我用源代码单卡训练全部数据集，参数都没有修改，训练150轮得到的结果跟论文里差距很大，得不到它训练的checkpoints评估得到的效果 ![monouni](https://private-user-images.githubusercontent.com/152282641/400419314-eaf4a1b5-e6d9-46c0-8c19-335f13bd0e00.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYxNjYyNzMsIm5iZiI6MTczNjE2NTk3MywicGF0aCI6Ii8xNTIyODI2NDEvNDAwNDE5MzE0LWVhZjRhMWI1LWU2ZDktNDZjMC04YzE5LTMzNWYxM2JkMGUwMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwNlQxMjE5MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zM2JiMDU2ZmRlNGY5MTAwMjM0ZmJhMmJjZmY1MmQ2MTVmZjU3ZmM0OWU0MjMzYTgxOWNiNWQ4ZjljZTdiODgzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.tF_PY-2PD4iXchNrLl1J-t89Tb0B_pkcwks6ATkO_fc)

可以分享一下你的系统设置吗？我代码能力稍微差一点希望能够相互沟通一下

**Comment by deyang2000** [comment]
> 可以分享一下你的系统设置吗？我代码能力稍微差一点希望能够相互沟通一下
由于时间比较久了，我已经清理了当时使用的虚拟环境。或许你可以根据GPU显存试试调节一下学习率，或者打印一下训练曲线。（作者使用的是4*V100（32G））

**Comment by mingjunjun** [comment]
> > 可以分享一下你的系统设置吗？我代码能力稍微差一点希望能够相互沟通一下
> > 由于时间比较久了，我已经清理了当时使用的虚拟环境。或许你可以根据GPU显存试试调节一下学习率，或者打印一下训练曲线。（作者使用的是4*V100（32G））

好的，谢谢
