### ISSUE TITLE
Evaluation results of DAIR-V2x-i

### ISSUE THREAD

**Issue by CleanSeaSalt** [Traffic-X/MonoUNI#5]
Hello, could you please provide MonoUNI's evaluation indicators for the two categories of Cyclist and Pedestrians on the DAIR-V2x-i data set? I seem to have only seen the category of motor vehicles in the paper：
![image](https://github.com/Traffic-X/MonoUNI/assets/53559220/0b68579f-79c1-4754-8e94-f7c21a0a25a2)
![image](https://github.com/Traffic-X/MonoUNI/assets/53559220/d3850294-bef7-43e7-b115-d7680e62dfab)

**Comment by jjrCN** [comment]
Results for Pedestrians and Cyclist are not retained. We will add more results later. Thank you

**Comment by yfCheng-CUMTB** [comment]
> Hello, could you please provide MonoUNI's evaluation indicators for the two categories of Cyclist and Pedestrians on the DAIR-V2x-i data set? I seem to have only seen the category of motor vehicles in the paper： ![image](https://github.com/Traffic-X/MonoUNI/assets/53559220/0b68579f-79c1-4754-8e94-f7c21a0a25a2) ![image](https://github.com/Traffic-X/MonoUNI/assets/53559220/d3850294-bef7-43e7-b115-d7680e62dfab)

您好，请问您复现出dairv2x数据集的结果了吗
