### ISSUE TITLE
关于rope.py中几个代码实现的问题

### ISSUE THREAD

**Issue by XuelianZ** [Traffic-X/MonoUNI#7]
你好，感谢开源，我仔细阅读代码产生了几个疑惑：
1.在rope3d.py 第 407行代码，tan_roi[h_r, w_r] = (y1_cur - calib.P2[1, 2]) * 1.0 / calib.P2[1,1]，请问这里为什么使用的是calib.P2[1,1]，我理解这里的calib.P2[1,1] 相当于相机内参的fy，与论文中提到的f好像不一致

2. 代码中使用了      min_f = 2250，max_f = 2800，请问这两个数是基于rope3D统计出来的相机焦距范围吗？

4. 在阅读以下代码段时产生了极大困惑，配置文件中interval_max、interval_min的设置依据是什么呢？代码段中的+4.5，-4.5是？
`if depth_ * _crop_ratio * fp / norm_theat_center3d < self.interval_max[0] / min_f:
                    vis_depth[i,0] = (vis_depth_roi* _crop_ratio * fp / norm_theta - (self.interval_min[0]-4.5) / max_f) / ((self.interval_max[0]+4.5) / min_f - (self.interval_min[0]-4.5) / max_f)
                    att_depth[i,0] = depth[i] -  vis_depth_roi
                    depth_bin_ind[i,0] = 1
                    depth_mask[i,0] = vis_depth_roi_ind
......

                if depth_ * _crop_ratio * fp / norm_theat_center3d >  self.interval_min[4] / max_f and depth_  * _crop_ratio * fp / norm_theat_center3d <  self.interval_max[4]/min_f:
                    vis_depth[i,4] = (vis_depth_roi * _crop_ratio * fp / norm_theta - ((self.interval_min[4]-4.5) / max_f)) / ((self.interval_max[4]+4.5) / min_f - (self.interval_min[4]-4.5) / max_f)
                    att_depth[i,4] = depth[i] -  vis_depth_roi
                    depth_bin_ind[i,4] = 1
                    depth_mask[i,4] = vis_depth_roi_ind`

十分期待您的答复~

**Comment by jjrCN** [comment]
1、fy就是相机的内参，是y方向上的焦距，因为公式的投影关系实际上是在y方向上计算的，所以用的fy。一般来说fx和fy也是基本相等的。
2、对
3、这部分是分区间学习归一化深度的代码，interval_min和interval_max是按照数据集障碍物的深度分布平均分的，分了5个区间。+4.5和-4.5也是超参，是为了防止障碍物表面的立体深度出现越界（越界到临近区间），因为深度区间是根据障碍物底面中心点深度划分的，但障碍物表面深度（比如车头或车尾）距离中心点一般也不会超出+-4.5m

**Comment by XuelianZ** [comment]
十分感谢！
